create database ProjectSouls;
use ProjectSouls;--
-- drop database ProjectSouls;
create table Armas (
idArma int primary key auto_increment,
nome varchar(64),
tipo varchar(30),
peso decimal(3,1),
DanoFisico int,
DanoMagico int,
DanoFlamejante int,
DanoEletrico int,
DanoSombrio int,
Critico int,
BuffMagia int
);



insert into Armas values
(null,'Dagger','Adaga', 1.5, 65, null, null, null, null, 130, null),
(null,'Parrying Dagger','Adaga', 1, 60, null, null, null, null, 110, null),
(null,'Mail Breaker','Adaga', 1.5, 89, null, null, null, null, 125, null),
(null,'Bandit knife','Adaga', 1.5, 79, null, null, null, null, 110, null),
(null,'Rotten Ghru Dagger','Adaga', 2, 64, null, null, null, null, 100, null),
(null,'Corvian GreatKnife','Adaga', 2.5, 93, null, null, null, null, 110, null),
(null,'Handmaid Dagger','Adaga', 0.5, 85, null, null, null, null, 110, null),
(null,'Scholar Candlestick','Adaga', 1.5, 68, null, null, null, null, 115, null),
(null,'Tailbone Short Sword','Adaga', 2, 106, null, null, null, null, 110, null),
(null,'Brigand Twindaggers','Adaga', 2.5, 70, null, null, null, null, 125, null),
(null,'Harpe','Adaga', 1.5, 62, null, null, null, null, null, null),
(null,'Aquamarine Dagger','Adaga', 1.5, 67, 67, null, null, null, 100, null),
(null,'Murky Hand Scythe','Adaga', 2, 72, null, null, null, 22, 100, null),
(null,'Shortsword','Espada Reta', 2, 99, null, null, null, null, 110, null),
(null,'Long Sword','Espada Reta', 3, 110, null, null, null, null, 100, null),
(null,'BroadSword','Espada Reta', 3, 117, null, null, null, null, 100, null),
(null,'Broken Straight Sword','Espada Reta', 1, 70, null, null, null, null, 100, null),
(null,'Astora Straight Sword','Espada Reta', 3, 129, null, null, null, null, 100, null),
(null,'Lothric Knight Sword','Espada Reta', 4, 103, null, null, null, null, 110, null),
(null,'Barbed Straight Sword','Espada Reta', 3, 111, null, null, null, null, 100, null),
(null,'Dark Sword','Espada Reta', 4.5, 110, null, null, null, null, 100, null),
(null,'Cleric Candlestick','Espada Reta', 2, 70, 77, null, null, null, 100, null),
(null,'Irithyll Straight Sword','Espada Reta', 4, 124, null, null, null, null, 100, null),
(null,'Anri Straight Sword','Espada Reta', 3, 117, null, null, null, null, 100, null),
(null,'Sunlight Straight Sword','Espada Reta', 3, 112, null, null, null, null, 100, null),
(null,'Morion Blade','Espada Reta', 4, 131, null, null, null, null, 100, null),
(null,'Lothric Holy Sword','Espada Reta', 4, 107, null, null, null, null, 100, null),
(null,'Gotthard Twinswords','Espada Reta', 6.5, 100, null, null, null, null, 100, null),
(null,'Valorheart','Espada Reta', 5.5, 120, null, null, null, null, 100, null),
(null,'Ringed Knight Stright Sword','Espada Reta', 4.5, 120, null, 11, null, null, 100, null),
(null,'Bastard Sword','Grande Espada', 8, 138, null, null, null, null, 100, null),
(null,'Claymore','Grande Espada', 9, 138, null, null, null, null, 100, null),
(null,'HollowSlayer Greatsword','Grande Espada', 8.5, 145, null, null, null, null, 100, null),
(null,'Firelink Greatsword','Grande Espada', 9, 128, null, 89, null, null, 100, null),
(null,'Black Knight Sword','Grande Espada', 10, 173, null, null, null, null, 100, null),
(null,'Flamberge','Grande Espada', 8.5, 158, null, null, null, null, 100, null),
(null,'Executioner Greatsword','Grande Espada', 9, 131, null, null, null, null, 100, null),
(null,'Wolf Knight Greatsword','Grande Espada', 11.5, 139, null, null, null, null, 100, null),
(null,'Wolnir Holy Sword','Grande Espada', 7.5, 151, null, null, null, null, 100, null),
(null,'Greatsword Of Judgment','Grande Espada', 9, 111, 86, null, null, null, 100, null),
(null,'Storm Ruler','Grande Espada', 8, 143, null, null, null, null, 100, null),
(null,'Moonlight Greatsword','Grande Espada', 10.5, 69, 130, null, null, null, 100, null),
(null,'Twin Princes Greatsword','Grande Espada', 9.5, 126, null, 83, null, null, 100, null),
(null,'Drakeblood Greatsword','Grande Espada', 6, 89, 71, null, 71, null, 100, null),
(null,'Onyx Blade','Grande Espada', 9, 80, null, null, null, 115, 100, null),
(null,'Gael Greatsword','Grande Espada', 9, 147, null, null, null, null, 100, null),
(null,'Zweihander','Ultra Espada Grande', 10, 145, null, null, null, null, 100, null),
(null,'Greatsword','Ultra Espada Grande', 20, 159, null, null, null, null, 100, null),
(null,'Astora Greatsword','Ultra Espada Grande', 8, 132, null, null, null, null, 100, null),
(null,'Farron Greatsword','Ultra Espada Grande', 12.5, 141, null, null, null, null, 100, null),
(null,'Fume Ultra Greatsword','Ultra Espada Grande', 25.5, 149, null, null, null, null, 100, null),
(null,'Profaned Greatsword','Ultra Espada Grande', 13.5, 161, null, null, null, null, 100, null),
(null,'Cathedral Knight Greatsword','Ultra Espada Grande', 15, 149, null, null, null, null, 100, null),
(null,'Black Knight Greatsword','Ultra Espada Grande', 16, 185, null, null, null, null, 100, null),
(null,'Lorian Greatsword','Ultra Espada Grande', 14, 151, null, 79, null, null, 100, null),
(null,'Lothric Knight Greatsword','Ultra Espada Grande', 16.5, 131, null, null, 87, null, 100, null),
(null,'Ringed Knight Paired Greatswords','Ultra Espada Grande', 22.5, 185, null, 11, null, null, 100, null),
(null,'Crescent Moon Sword','Espada Curva', 2.5, 78, 78, null, null, null, 100, null),
(null,'Scimitar','Espada Curva', 2.5, 90, null, null, null, null, 100, null),
(null,'Pontiff Knight Curved Sword','Espada Curva', 3.5, 12, null, null, null, null, 100, null),
(null,'Falchion','Espada Curva', 4, 117, null, null, null, null, 100, null),
(null,'Sellsword Twinblades','Espada Curva', 5.5, 99, null, null, null, null, 100, null),
(null,'Warden Twinblades','Espada Curva', 6.5, 93, null, null, null, null, 100, null),
(null,'Shotel','Espada Curva', 2.5, 104, null, null, null, null, 100, null),
(null,'Painting Guardiand Curved Sword','Espada Curva', 1.5, 88, null, null, null, null, 100, null),
(null,'Dancer Enchanted Swords','Espada Curva', 8.5, 79, 62, 62, null, null, 100, null),
(null,'Storm Curved Sword','Espada Curva', 5, 110, null, null, null, null, 100, null),
(null,'Carthus Curved Sword','Espada Curva', 5.5, 105, null, null, null, null, 100, null),
(null,'Carthus Shotel','Espada Curva', 3, 106, null, null, null, null, 100, null),
(null,'Rotten Ghru Curved Sword','Espada Curva', 2, 103, null, null, null, null, 100, null),
(null,'Follower Sabre','Espada Curva', 4, 112, null, null, null, null, 100, null),
(null,'Demon Scar','Espada Curva', 0.5, 0, null, 99, null, null, 110, 110),
(null,'Murakumo','Grande Espada Curva', 11, 132, null, null, null, null, 100, null),
(null,'Exile Greatsword','Grande Espada Curva', 17, 148, null, null, null, null, 100, null),
(null,'Old Wolf Curved Sword','Grande Espada Curva', 13, 155, null, null, null, null, 100, null),
(null,'Carthus Curved Greatsword','Grande Espada Curva', 10.5, 122, null, null, null, null, 100, null),
(null,'Harald Curved Greatsword','Grande Espada Curva', 14, 140, null, null, null, null, 100, null),
(null,'Darkdrift','Katana', 3.5, 134, null, null, null, null, 100, null),
(null,'Uchigatana','Katana', 5.5, 115, null, null, null, null, 100, null),
(null,'Washing Pole','Katana', 8.5, 121, null, null, null, null, 100, null),
(null,'Onikiri And Ubadachi','Katana', 8.5, 104, null, null, null, null, 100, null),
(null,'Black Blade','Katana', 6.5, 122, null, null, null, null, 100, null),
(null,'Chaos Blade','Katana', 6, 103, null, null, null, null, 100, null),
(null,'Bloodlust','Katana', 5, 105, null, null, null, null, 100, null),
(null,'Frayed Blade','Katana', 8, 101, null, null, null, 41, 100, null),
(null,'Estoc','Lamina de impulso', 3.5, 105, null, null, null, null, 100, null),
(null,'Rapier','Lamina de impulso', 2, 95, null, null, null, null, 130, null),
(null,'Ricard Rapier','Lamina de impulso', 2.5, 97, null, null, null, null, 100, null),
(null,'Crystal Sage Rapier','Lamina de impulso', 2.5, 55, 82, null, null, null, 100, null),
(null,'Irithyll Rapier','Lamina de impulso', 3, 116, null, null, null, null, 110, null),
(null,'Crow Quills','Lamina de impulso', 4, 98, null, null, null, null, 120, null),
(null,'Battle Axe','Machado', 4, 125,  null, null, null, null, 100, null),
(null,'Hand Axe','Machado', 2.5, 110,  null, null, null, null, 100, null),
(null,'Thrall Axe','Machado', 1.5, 104,  null, null, null, null, 100, null),
(null,'Brigand Axe','Machado', 3, 124,  null, null, null, null, 100, null),
(null,'Dragonslayer Axe','Machado', 4, 105,  null, null, 105, null, 100, null),
(null,'Butcher Knife','Machado', 7, 95,  null, null, null, null, 100, null),
(null,'Winged Knight Twinaxes','Machado', 8.5, 122,  null, null, null, null, 100, null),
(null,'Eleonora','Machado', 6.5, 156,  null, null, null, null, 100, null),
(null,'Man Serpent Hatchet','Machado', 4, 125,  null, null, null, null, 100, null),
(null,'Millwood Battle Axe','Machado', 6.5, 135,  null, null, null, null, 100, null),
(null,'Greataxe','Grande Machado', 16, 188,  null, null, null, null, 100, null),
(null,'Dragonslayer Greataxe','Grande Machado', 20, 200,  null, null, 74, null, 100, null),
(null,'Demon Greataxe','Grande Machado', 14.5, 157,  null, 88, null, null, 100, null),
(null,'Great Machete','Grande Machado', 14, 167,  null, null, null, null, 100, null),
(null,'Yhorm Great Machete','Grande Machado', 19, 185,  null, null, null, null, 100, null),
(null,'Black Knight Greataxe','Grande Machado', 19.5, 216,  null, null, null, null, 100, null),
(null,'Earth Seeker','Grande Machado', 17, 154,  null, null, null, null, 100, null),
(null,'Club','Martelo', 2.5, 108,  null, null, null, null, 100, null),
(null,'Drang Hammers','Martelo', 9, 110,  null, null, null, null, 100, null),
(null,'Mace','Martelo', 5, 115,  null, null, null, null, 100, null),
(null,'Morning Star','Martelo', 5, 122,  null, null, null, null, 100, null),
(null,'Reinford Club','Martelo', 4, 108,  null, null, null, null, 100, null),
(null,'Heysel Pick','Martelo', 4.5, 93,  70, null, null, null, 100, null),
(null,'Warpick','Martelo', 4.5, 113,  null, null, null, null, 100, null),
(null,'Blacksmith Ghammer','Martelo', 5, 105,  null, null, null, null, 100, null),
(null,'Gargoyle Flame Hammer','Grande Martelo', 11, 122,  null, 100, null, null, 100, null),
(null,'Great Mace','Grande Martelo', 18, 173,  null, null, null, null, 100, null),
(null,'Large Club','Grande Martelo', 10, 148,  null, null, null, null, 100, null),
(null,'Vordt Great Hammer','Grande Martelo', 17, 176,  null, null, null, null, 100, null),
(null,'Morne Great Hammer','Grande Martelo', 24, 200,  null, null, null, null, 100, null),
(null,'Great Wooden Hammer','Grande Martelo', 8, 125,  null, null, null, null, 100, null),
(null,'Great Club','Grande Martelo', 12, 152,  null, null, null, null, 100, null),
(null,'Smough Great Hammer','Grande Martelo', 24, 205,  null, null, null, null, 100, null),
(null,'Old King Great Hammer','Grande Martelo', 18.5, 180,  null, 69, null, null, 100, null),
(null,'Pickaxe','Grande Martelo', 8, 140,  null, null, null, null, 100, null),
(null,'Dragon Tooth','Grande Martelo', 21, 188,  null, null, null, null, 100, null),
(null,'Spiked Mace','Grande Martelo', 16, 149,  null, null, null, null, 100, null),
(null,'QuakeStone Hammer','Grande Martelo', 15, 189,  null, null, null, null, 100, null),
(null,'Great Mace','Grande Martelo', 18, 173,  null, null, null, null, 100, null),
(null,'Caestus','Punho&Garra', 0.5, 91,  null, null, null, null, 100, null),
(null,'Demon Fist','Punho&Garra', 5.5, 111,  null, 77, null, null, 100, null),
(null,'Dark Hand','Punho&Garra', 0, 88,  null, null, null, 150, 100, null),
(null,'Claw','Punho&Garra', 1.5, 86,  null, null, null, null, 110, null),
(null,'Manikin Claws','Punho&Garra', 1.5, 81,  null, null, null, null, 110, null),
(null,'Crow Talons','Punho&Garra', 3, 91,  null, null, null, null, 110, null),
(null,'Arstor Spear','Lança', 6.5, 118,  null, null, null, null, 100, null),
(null,'Drang Twinspears','Lança', 8, 100,  null, null, null, null, 100, null),
(null,'Gargoyle Flame Spear','Lança', 9.5, 103,  null, 90, null, null, 100, null),
(null,'Spear','Lança', 4.5, 104,  null, null, null, null, 100, null),
(null,'Tailbone Spear','Lança', 4.5, 118,  null, null, null, null, 100, null),
(null,'Pike','Lança', 7.5, 105,  null, null, null, null, 100, null),
(null,'Winged Spear','Lança', 6, 95,  null, null, null, null, 100, null),
(null,'Four-Pronged Plow','Lança', 6.5, 105,  null, null, null, null, 100, null),
(null,'Saint Bident','Lança', 8.5, 98,  null, null, null, null, 100, null),
(null,'Rotten Ghru Spear','Lança', 5.5, 104,  null, null, null, null, 100, null),
(null,'Partizan','Lança', 6.5, 108,  null, null, null, null, 100, null),
(null,'Yorshkas Spear','Lança', 6.5, 102,  null, null, null, null, 100, null),
(null,'Dragonslayer Spear','Lança', 9.5, 113,  null, null, 70, null, 100, null),
(null,'Dragon SwordSpear','Lança', 14.5, 128,  null, null, 34, null, 100, null),
(null,'Golden Ritual Spear','Lança', 3, 73,  77, null, null, null, 100, null),
(null,'Soldering Iron','Lança', 5, 39,  null, 96, null, null, 100, null),
(null,'Lothric Knight Long Spear','Lança', 8, 112,  null, null, null, null, 100, null),
(null,'Greatlance','Lança', 10.5, 129,  null, null, null, null, 100, null),
(null,'Follower Javelin','Lança', 4, 106,  null, null, null, null, 100, null),
(null,'Lothric War Banner','Lança', 5, 100,  null, null, null, null, 100, null),
(null,'Ringed Knight Spear','Lança', 9, 126,  null, 12, null, null, 100, null),
(null,'Halberd','Alabarda', 8, 125,  null, null, null, null, 100, null),
(null,'Lucerne','Alabarda', 7.5, 126,  null, null, null, null, 100, null),
(null,'Winged Knight Halberd','Alabarda', 14, 145,  null, null, null, null, 100, null),
(null,'Red Hilted Halberd','Alabarda', 8, 130,  null, null, null, null, 100, null),
(null,'Glaive','Alabarda', 11, 141,  null, null, null, null, 100, null),
(null,'Crescent Axe','Alabarda', 6, 119,  null, null, null, null, 100, null),
(null,'Gundyr Halberd','Alabarda', 13, 145,  null, null, null, null, 100, null),
(null,'Black Knight Glaive','Alabarda', 9, 159,  null, null, null, null, 100, null),
(null,'Immolation Tinder','Alabarda', 10, 118,  null, 75, null, null, 100, null),
(null,'Splitleaf Greatsword','Alabarda', 13.5, 132,  null, null, null, null, 100, null),
(null,'Crucifix Of The Mad King','Alabarda', 12, 124,  null, null, null, 74, 100, null),
(null,'Great Scythe','Foice', 7, 105,  null, null, null, null, 100, null),
(null,'Pontiff Knight Great Scythe','Foice', 7.5, 100,  null, null, null, null, 100, null),
(null,'Great Corvian Scythe','Foice', 9, 97,  null, null, null, null, 100, null),
(null,'Friede Great Scythe','Foice', 13, 110, 77, null, null, null, 100, null),
(null,'Whip','Chicote', 2, 90,  null, null, null, null, 100, null),
(null,'Notched Whip','Chicote', 2, 95,  null, null, null, null, 100, null),
(null,'Witch Lock','Chicote', 3, 77,  null, 80, null, null, 100, null),
(null,'Spotted Whip','Chicote', 2.5, 102,  null, null, null, null, 100, null),
(null,'Rose Of Ariandel','Chicote', 3.5, 79,  null, null, null, null, 100, null),
(null,'Black Bow Of Pharis','Arco', 3, 67,  null, null, null, null, 100, null),
(null,'Longbow','Arco', 4, 82,  null, null, null, null, 100, null),
(null,'Short Bow','Arco', 2, 77,  null, null, null, null, 100, null),
(null,'Dragonrider Bow','Arco', 6.5, 110,  null, null, null, null, 100, null),
(null,'Composite Bow','Arco', 3.5, 73,  null, null, null, null, 100, null),
(null,'Darkmoon Longbow','Arco', 4.5, 36,  44, null, null, null, 100, null),
(null,'White Birch Bow','Arco', 2.5, 82,  null, null, null, null, 100, null),
(null,'Onislayer Greatbow','Grande Arco', 7.5, 111,  null, null, null, null, 100, null),
(null,'Dragonslayer Greatbow','Grande Arco', 10, 126,  null, null, null, null, 100, null),
(null,'Millwood Greatbow','Grande Arco', 9, 139,  null, null, null, null, 100, null),
(null,'Light Crossbow','Besta', 3, 64,  null, null, null, null, 100, null),
(null,'Knight Crossbow','Besta', 4, 40,  null, null, 40, null, 100, null),
(null,'Arbalest','Besta', 6, 78,  null, null, null, null, 100, null),
(null,'Sniper Crossbow','Besta', 7.5, 70,  null, null, null, null, 100, null),
(null,'Avelyn','Besta', 7.5, 64,  null, null, null, null, 100, null),
(null,'Heavy Crossbow','Besta', 4.5, 72,  null, null, null, null, 100, null),
(null,'Repeating Crossbow','Besta', 7.5, 83,  null, null, null, null, 100, null),
(null,'Sorcerer Staff','Cajado', 2, 60,  null, null, null, null, 100, 100),
(null,'Heretic Staff','Cajado', 3, 63,  null, null, null, null, 100, 113),
(null,'Witchtree Branch','Cajado', 2, 57,  null, null, null, null, 100, 114),
(null,'Sage Crystal Staff','Cajado', 2.5, 84,  null, null, null, null, 100, 60),
(null,'Izalith Staff','Cajado', 3, 120,  null, null, null, null, 100, 130),
(null,'Court Sorcerer Staff','Cajado', 2, 60,  null, null, null, null, 100, 105),
(null,'Man-Grub Staff','Cajado', 3, 90,  null, null, null, null, 100, 100),
(null,'Storyteller Staff','Cajado', 2.5, 60,  null, null, null, null, 100, 60),
(null,'Mendicant Staff','Cajado', 2.5, 60,  null, null, null, null, 100, 55),
(null,'Archdeacon Great Staff','Cajado', 2.5, 89,  null, null, null, null, 100, 118),
(null,'Murky Longstaff','Cajado', 3, 86,  null, null, null, null, 100, 55),
(null,'Preacher Right Arm','Cajado', 2, 109,  null, null, null, null, 100, 60),
(null,'Pyromancy Flame','Chama', 0, null,  null, 100, null, null, 100, 144),
(null,'Pyromancy Parting Flame','Chama', 0, null,  null, 110, null, null, 100, 130),
(null,'Talisman','Talismã', 0.5, 52,  null, null, null, null, 100, 100),
(null,'Saint Talisman','Talismã', 0.5, 53,  null, null, null, null, 100, 100),
(null,'Sunlight Talisman','Talismã', 0.5, 53,  null, null, null, null, 100, 60),
(null,'Canvas Talisman','Talismã', 0.5, 52,  null, null, null, null, 100, 112 ),
(null,'White Hair Talisman','Talismã', 0.5, 73,  null, 79, null, null, 100, 20),
(null,'Sunless Talisman','Talismã', 0.5, 74,  null, null, null, null, 100, 60),
(null,'Cleric Sacred Chime','Carrilhão', 0.5, 52,  null, null, null, null, 100, 135),
(null,'Priest Chime','Carrilhão', 0.5, 52,  null, null, null, null, 100, 118),
(null,'Crystal Chime','Carrilhão', 0.5, 73,  null, null, null, null, 100, 20),
(null,'Caitha Chime','Carrilhão', 0.5, 74,  null, null, null, null, 100, 60),
(null,'Saint-Tree Bellvine','Carrilhão', 0.5, 52,  null, null, null, null, 100,  100),
(null,'Yorshka Chime','Carrilhão', 0.5, 54,  null, null, null, null, 100, 60),
(null,'Sacred Chime Of Filianore','Carrilhão', 0.5, 74,  null, null, null, null, 100, 142);

insert into Magias values
-- (null, 'nome', 'tipo', 'descriçao', dano, cura, buff),
(null, 'Heal Aid', 'Milagre', ' Significantemente restaura HP', null, 1.1, null),
(null, 'Heal', 'Milagre', 'Restaura o próprio HP e de todos proximos', null, 3, null),
(null, 'Med Heal', 'Milagre', 'Moderadamente restaura HP próprio e de todos proximos', null, 4.1, null),
(null, 'Great Heal', 'Milagre', 'Restaura muito HP próprio e de todos próximos', null, 5.5, null),
(null, 'Shooting Sunlight', 'Milagre', ' Restaura muito HP em todos na área', null, 7, null),
(null, 'Replenishment', 'Milagre', 'Gradualmente cura 5HP por segundo', null, null, null),
(null, 'Bountiful Light', 'Milagre', 'Gradualmente cura 5HP por segundo', null, null, null),
(null, 'Caressing Tears', 'Milagre', 'Retira efeitos de sangramento, veneno e congelamento de todos próximos', null, null, null),
(null, 'Tears Of Denial', 'Milagre', 'Garante a chance de sobreviver ao alcançar 0HP', null, null, null),
(null, 'Homeward', 'Milagre', 'Retorna o conjurador a ultima fogueira em que ele descansou', null, null, null),
(null, 'Seek Guidance', 'Milagre', 'Exibe maís sinais de ajuda de outros mundos', null, null, null),
(null, 'Sacred Oath', 'Milagre', 'Aumenta 10% de dano fisico e 10% de abosorção para todos os tipos de dano', 1.1, null, 1.1),
(null, 'Force', 'Milagre', 'Emite uma onda de choque que repulsa inimigos e projéteis próximos ', null, null, null),
(null, 'Emit Force', 'Milagre', 'Emita uma onda de choque frontalmente', 1.2, null, null),
(null, 'Wrath of The Gods', 'Milagre', 'Emite uma poderosa onda de choque', 3.2, null, null),
(null, 'Lightning Spear', 'Milagre', 'Arremessa uma lança de raio', 1.45, null, null),
(null, 'Great Lightning Spear', 'Milagre', 'Arremessa uma lança de raio', 1.85, null, null),
(null, 'Sunlight Spear', 'Milagre', 'Arremessa uma lança de raio solar', 2.6, null, null),
(null, 'Lightning Stake', 'Milagre', 'Finca uma estaca de raio no chão, dando dano em volta', 1.3, null, null),
(null, 'Lightning Storm', 'Milagre', 'Provoca uma chuva de raios', 2.35, null, null),
(null, 'Divine Pillars of Light', 'Milagre', 'Evoca mult', 1.9, null, null),
(null, 'Blessed Weapon', 'Milagre', 'Abençoa a arma direita, acrescentando dano e gradualmente recuperando HP', 0.75, null, null),
(null, 'Lightning Blade', 'Milagre', 'Imbuí a arma direita com raios', 0.95, null, null),
(null, 'Darkmoon Blade', 'Milagre', 'Imbuí a arma direita com a magia de Darkmoon', 0.95, null, null),
(null, 'Magic Barrier', 'Milagre', 'Aumenta a absorção de dano magico, se cobrindo com uma proteção branca', null, null, 1.35),
(null, 'Great Magic Barrier', 'Milagre', 'Aumenta muito a absorção de dano magico, se cobrindo com uma proteção branca', null, null, 1.35),
(null, 'Dark Blade', 'Milagre', 'Imbuí a arma direita com escuridão', 0.85, null, null),
(null, 'Vow Of Silence', 'Milagre', 'Previne o uso de magia na area', null, null, null),
(null, 'Dead again', 'Milagre', 'Abençoa corpos, transformando eles em armadilhas', null, null, 1.35),
(null, 'Atonement', 'Milagre', 'Atraí mais atenção de terceiros', null, null, null),
(null, 'Deep Protection', 'Milagre', 'Significantemente aumenta o dano, absorção e resistencia de dano, enquanto aumenta a recuperação de estamina', 1.05, null, 0.05),
(null, 'Gnaw', 'Milagre', 'Sumona um enxame de insetos', 0.9, null, null),
(null, 'Dorhys Gnawing', 'Milagre', 'Sumona um enorme enxame de insetos', 1.2, null, null),
(null, 'Lifehunt Scythe', 'Milagre', 'Rouba HP ao usar uma foice ilusória', 2, null, null),
(null, 'Way Of White Corona', 'Milagre', 'Fragmentos de discos brancos voam e retornam ao conjurador', 0.85, null, null),
(null, 'Projected Heal', 'Milagre', 'Projeta uma magia de cura na área', null, 1.7, null),
(null, 'Lightning Arrow', 'Milagre', 'Atira flechas de luz', 1.6, null, null),
(null, 'Fireball', 'Piromancia', 'Arremessa uma bola de fogo', 1.7, null, null),
(null, 'Fire Orb', 'Piromancia', 'Arremessa um enorme orbe de fogo', 2.25, null, null),
(null, 'Bursting Fireball', 'Piromancia', 'Arremessa uma enchurrada de bolas de fogo explosivas', 0.71, null, null),
(null, 'Great Chaos Fire Orb', 'Piromancia', 'Arremessa um enorme orbe caótico de chamas', 3.3, null, null),
(null, 'Chaos Bed Vestiges', 'Piromancia', 'Arremessa chamas caóticas que queimam as redondezas', 3.4, null, null),
(null, 'Fire Surge', 'Piromancia', 'Emite uma rajada de fogo constante', 0.67, null, null),
(null, 'Fire Whip', 'Piromancia', 'O conjurador manipula a direção das chamas', 0.65, null, null),
(null, 'Firestorm', 'Piromancia', 'Emergem multiplos pilares de chama em volta do conjurador ', 1.75, null, null),
(null, 'Chaos Storm', 'Piromancia', 'Chamas caóticas derretem até grandes rochas e criam uma breve onda de lava derretida com o impacto', 1.95, null, null),
(null, 'Great Combustion', 'Piromancia', 'Cria uma poderosa e gigante chama em sua mão', 1.95, null, null),
(null, 'Sacred Flame', 'Piromancia', 'Queima o alvo de dentro para fora com apenas um toque', 2.3, null, null),
(null, 'Profaned Flame', 'Piromancia', 'Engolfa inimigos no alcance e os queima até as cinzas', 2.6, null, null),
(null, 'Poison Mist', 'Piromancia', 'Cria uma névoa venenosa', null, null, null),
(null, 'Toxic Mist', 'Piromancia', 'Cria uma densa névoa venenosa ', null, null, null),
(null, 'Acid Surge', 'Piromancia', 'Emite um acido que corrói armas e armaduras', null, null, null),
(null, 'Flash Sweat', 'Piromancia', 'Intensifica o suor corporal, amentando a absorção de dano de flamejante', null, null, 0.3),
(null, 'Profuse Sweat', 'Piromancia', 'Aumenta temporareamente a resistencia a sangramento, veneno, congelamento e maldições', null, null, null),
(null, 'Power Within', 'Piromancia', 'Temporariamente aumenta o ataque, mas perde HP gradualmetne', 0.2, null, null),
(null, 'Carthus Beacon', 'Piromancia', 'Acrescenta dano com ataques consecutivos', 0.15, null, null),
(null, 'Carthus Flame Arc', 'Piromancia', 'Imbuí a arma direita em chamas', 0.9, null, null),
(null, 'Warmth', 'Piromancia', 'Cria uma gentil e calorosa chama que cura quem a toca', null, null, null),
(null, 'Rapport', 'Piromancia', 'Encanta o inimigo tornando-o temporariamente em um aliado', null, null, null),
(null, 'Boulder Heave', 'Piromancia', 'Espele uma rocha de sua boca', 1.8, null, null),
(null, 'Black Flame', 'Piromancia', 'Cria uma enorme e sombria chama na mão', 2.4, null, null),
(null, 'Black Fire Orb', 'Piromancia', 'Arremessa uma bola de fogo negra', 2.4, null, null),
(null, 'Black Serpent', 'Piromancia', 'Libera chamas negras e onduladas pelo chão', 1.65, null, null),
(null, 'Floating Chaos', 'Piromancia', 'Sumona um orbe caótico que arremessa orbes de fogo', 0.85, null, null),
(null, 'Seething Chaos', 'Piromancia', 'Arremessa um aglomerado fervente explosivo', 2, null, null),
(null, 'Flame Fan', 'Piromancia', 'Libera uma ventoada de chamas sobre o conjurador', 1.55, null, null),

select * from Armas;
select * from Magia;

select * from Armas
	where tipo = 'Adaga';
select * from Armas
	where tipo = 'Espada Reta';
select * from Armas
	where tipo = 'Grande Espada';
select * from Armas
	where tipo = 'Ultra Espada Grande';
select * from Armas
	where tipo = 'Espada Curva';
select * from Armas
	where tipo = 'Grande Espada Grande';
select * from Armas
	where tipo = 'Katana';
select * from Armas
	where tipo = 'Lamina de impulso';
select * from Armas
	where tipo = 'Machado';
select * from Armas
	where tipo = 'Grande Machado';
select * from Armas
	where tipo = 'Martelo';
select * from Armas
	where tipo = 'Grande Martelo';
select * from Armas
	where tipo = 'Punho&Garra';
select * from Armas
	where tipo = 'Lança';
select * from Armas
	where tipo = 'Alabarda';
select * from Armas
	where tipo = 'Foice';
select * from Armas
	where tipo = 'Chicote';
select * from Armas
	where tipo = 'Arco';
select * from Armas
	where tipo = 'Grande Arco';
select * from Armas
	where tipo = 'Besta';
select * from Armas
	where tipo = 'Cajado';
select * from Armas
	where tipo = 'Chama';
select * from Armas
	where tipo = 'Talismã';
select * from Armas
	where tipo = 'Carrilhão';
    

